apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: litmus
  INFLUXDB_URL: http://project-metrics.examples.svc.cluster.local:8086
  INFLUXDB_USER: HEdz0ThbXf
  INFLUXDB_USER_PASSWORD: Q6pYSQ3n26
